name: genshin_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  contained_tab_bar_view: ^0.8.0
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  salomon_bottom_bar: ^3.3.2
  webview_flutter: ^4.4.2

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Genshin_Impact_logo.png
  color_dark: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
