# Lane to Deploy Production-Release Bundle file in Internal track
desc "Deploy Production-Release APK file in Internal track to PlayStore" 
lane :deploy do |options|
  supply(
      json_key_data: ENV['JSON_KEY_DATA'],
      track: 'internal',
      skip_upload_images: true,
      skip_upload_screenshots: true,
      package_name: 'com.deploy.verygoodcore.genshin_app.dev',
      aab_paths: ["build/app/outputs/bundle/developmentRelease/app-development-release.aab"]
  )
  # firebase_app_distribution(
  #   app: "1:643923406936:android:d1fc15e67f4c584f599a2d",
  #   firebase_cli_token: "1//0gZ-NxQE63hqKCgYIARAAGBASNwF-L9Ir23xAG_y1QprjRwWQOD-SlzCy-JUgN9uwXJlL0rb-MYZxZIfmv1c3xBZ_9pMMdvi9ZOw",
  #   android_artifact_type: "APK",
  #   release_notes: "RELEASE-NOTE",
  #   android_artifact_path: "build/app/outputs/flutter-apk/app-development-release.apk",
  #   groups: "genshinns-tester"
  # )
  end
