# Lane to Deploy Production-Release Bundle file in Internal track
desc "Deploy Production-Release APK file in Internal track to PlayStore" # Lane description
lane :deploy_development_release do |options|
   flutter_build
   gradle(
            task: "bundle", # assemble for release apk, assemble
            flavor: "development", # Flavor Name
            build_type: "Release",
            project_dir: "android",
            flags: "-Ptarget=lib/main_development.dart",
            properties: {
                "android.injected.signing.store.file" => ENV["ANDROID_SIGNING_KEY"],
                "android.injected.signing.store.password" => ENV["ANDROID_STORE_PASSWORD"],
                "android.injected.signing.key.alias" =>  ENV["ANDROID_KEY_ALIAS"],
                "android.injected.signing.key.password" =>  ENV["ANDROID_KEY_PASSWORD"],
            }
  )
  supply(
      skip_upload_images: 'true',
      skip_upload_screenshots: 'true',
      track:'internal', 
      package_name: 'com.deploy.verygoodcore.genshin_app.dev',
      aab_paths: ["build/app/outputs/bundle/developmentRelease/app-development-release.aab"]
  )
  # firebase_app_distribution(
  #   app: "1:643923406936:android:d1fc15e67f4c584f599a2d",
  #   firebase_cli_token: "1//0gZ-NxQE63hqKCgYIARAAGBASNwF-L9Ir23xAG_y1QprjRwWQOD-SlzCy-JUgN9uwXJlL0rb-MYZxZIfmv1c3xBZ_9pMMdvi9ZOw",
  #   android_artifact_type: "APK",
  #   release_notes: "RELEASE-NOTE",
  #   android_artifact_path: "build/app/outputs/flutter-apk/app-development-release.apk",
  #   groups: "genshinns-tester"
  # )
  end
